CREATE TABLE TDS_TB_mercado (
                                id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                nome    VARCHAR2(50) NOT NULL,
                                tipo    VARCHAR2(50) NOT NULL,
                                setor   VARCHAR2(255),
                                tamanho NUMBER,
                                preco   NUMBER NOT NULL
);