BEGIN
EXECUTE IMMEDIATE '
CREATE TABLE transacoes (
                            id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            descricao       VARCHAR2(255) NOT NULL,
                            valor           NUMBER(10,2),
                            data_transacao  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
END IF;
END;
/